### ISSUE TITLE
demo in the video

### ISSUE THREAD

**Issue by daodao316** [yewzijian/RPMNet#10]
is  demo.py here? I am a beginner and want to test your perfect work like your video ?

**Comment by yewzijian** [comment]
Hi, you can follow the evaluation workflow in the Readme using the provided pretrained checkpoint which will generate the pred_transforms.npy file that contains the output transforms.
You'll need to write your own visualization tool to visualize the registration. For the video, I used a custom visualizer which is built on top of [python vtk](https://pypi.org/project/vtk/) library.
