### ISSUE TITLE
Corresponding normals for the points

### ISSUE THREAD

**Issue by 5100117** [yewzijian/RPMNet#24]
Hi,

Thanks for sharing your work.
I saw that you are using xyz (XYZ coordinates of the points) and normals (Corresponding normals for the points) as input. May I ask what is "normals"? I want to use your model on my dataset which only has xyz coordinates, how can I create "normals coordinates" for my dataset.
Thank you,

**Comment by yewzijian** [comment]
[Normals](https://en.wikipedia.org/wiki/Normal_(geometry)) are the directions perpendicular to a given surface. You can compute them from point clouds by considering the local neighborhood of points. Many point cloud libraries, e.g. [Open3D](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.estimate_normals) provide such functionality.


Zi Jian

**Comment by 5100117** [comment]
I got it. Thank you very much.
