### ISSUE TITLE
Something about the code!

### ISSUE THREAD

**Issue by ZhileiChen99** [yewzijian/RPMNet#26]
Thank you for your wonderful work. I recently learn about your code of RPM, but I have one problem that confuses me, which is how to visualize the transformed src point cloud and the ref point cloud? My idea is that when testing, I save the transformed src point cloud and the ref point cloud, then use meshlab or other software to visualize them.

**Comment by yewzijian** [comment]
Yes you can save out the point clouds, or you can visualize them in the python code using Open3D or vtk.

**Comment by zhil-chen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you for your help!
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    On 12/18/2021 17:41，Zi Jian ***@***.***> wrote： 



Yes you can save out the point clouds, or you can visualize them in the python code using Open3D or vtk.

**Comment by 294coder** [comment]
收到
