### ISSUE TITLE
How to color the src and ref point clouds with learned features?

### ISSUE THREAD

**Issue by henryJhonOt** [yewzijian/RPMNet#29]
The input `train_data` in `model` contains `train_data['points_src']` of  `8x717x6` and `train_data['points_ref"]` of `8x717x6`.
I extracted the following feature for each sample as the author defined during learning:
```python
# feature returned by sample_and_group_multi()
feature_before_dim = {
    'xyz'  :     # an array of (717, 1, 3),
    'dxyz':     # an array of (717, 64, 3),
    'ppf':       # an array of (717, 64, 4)
}

# feature returned by FeatExtractionEarlyFusion.forward()
feature_after_dim     # an array of (717, 96)
```
Here's the problem. How either of the above two features help me color the 717 points in src clouds? It is expected that the points with similar features should share the same color. In other words, given `n` colors (blue, red, etc..), how to design a hash function `f` such that `f(feat) -> {0, 1, 2, ..., n-1}` maps the input `feat` to a particular color

**Comment by henryJhonOt** [comment]
I designed my own local feature of point clouds. Now I'm working on the comparison between other features and mine via coloring points with mapped color from learned features.

I've tried to set the `feat_dim=1` in `arguments.py`, but it did'nt work as anticipated.

**Comment by yewzijian** [comment]
Hi, if I understand correctly, you are trying to visualize the high dimensional features on the point cloud using color. 

- If you are discretizing it into n colors, you need to cluster the features into n clusters, and assign a different color to each of the clusters.
- If you are using a continuous RGB range, you'll first need to map the high dimensional feature spaces into three dimensions, e.g. using PCA or tSNE.


Zi Jian

**Comment by MR-hyj** [comment]
> 

Thanks. You've been very helpful. I will try PCA

**Comment by henryJhonOt** [comment]
> el

I will try PCA. Thank you. You've been very helpful
