### ISSUE TITLE
hwo to display the registed point cloud?

### ISSUE THREAD

**Issue by MrCrazyCrab** [yewzijian/RPMNet#3]
Thanks for you great work, i wonder how to display the registed point cloud? just like the video you have showed in the youtube.

**Comment by yewzijian** [comment]
You can use any tool that is able to visualize the Nx3 points as a point cloud.

For python, you can use [Open3D](http://www.open3d.org) or (the simpler) [vtk_visualizer](https://pypi.org/project/vtk_visualizer/). I personally use a custom version modified from vtk_visualizer's code.
