### ISSUE TITLE
Evaluated metrics are not meeting expectations

### ISSUE THREAD

**Issue by henryJhonOt** [yewzijian/RPMNet#30]
I trained the model for many times using the same metrics as proposed in RPMNet paper. However, I'm not getting an promising evaluating results.
Here is one of the evaluated results.
```python

# this model is trained on --noise_type clean --num_points 717

{
	"r_rmse": 30.818792915605933, 
	"r_mae": 23.835809988770535, 
	"t_rmse": 0.3206479847431183, 
	"t_mae": 0.25871723890304565, 
	"err_r_deg_mean": 46.72205352783203, 
	"err_r_deg_rmse": 51.79454803466797, 
	"err_t_mean": 0.5199803709983826, 
	"err_t_rmse": 0.5553786158561707, 
	"chamfer_dist": 0.12541979551315308
}
```

All metrics are so far away from those in paper:
![image](https://user-images.githubusercontent.com/46344518/164735414-82ca9739-e0bd-47ce-8759-a840dd9cc1a7.png)

I don't think I've changed the codes which calculates the metrics. But however I tried, the results were just not good enough.

**Comment by yewzijian** [comment]
This is weird. The model in Table 1 is trained using 1024 points. Nevertheless, even with 717 points the model should still deliver good accuracies. I just did a quick retraining with 717 points. In the first validation run after 4 training epochs, the mean validation rotation error is already below 2 deg. The test set accuracy is also similar.

You might want to check the code.

**Comment by henryJhonOt** [comment]
> This is weird. The model in Table 1 is trained using 1024 points. Nevertheless, even with 717 points the model should still deliver good accuracies. I just did a quick retraining with 717 points. In the first validation run after 4 training epochs, the mean validation rotation error is already below 2 deg. The test set accuracy is also similar.
> 
> You might want to check the code.

I'm truly grateful to your efforts and reply. I re-tested the matric-calculating codes with both rot_mag and trans_mag is 0, but still not working. I am checking the codes again. Thank you!
