### ISSUE TITLE
shape_names.txt

### ISSUE THREAD

**Issue by KuZongFan** [yewzijian/RPMNet#39]
Hello, I would like to ask you        
with open(os.path.join(dataset_path, 'shape_names.txt')) as fid:
            self._classes = [l.strip() for l in fid]
            self._category2idx = {e[1]: e[0] for e in enumerate(self._classes)}
            self._idx2category = self._classes
Where to get the shape_names.txt files in the code

**Comment by yewzijian** [comment]
Hi. That file is part of the dataset, which should be automatically
downloaded when you run the code.

**Comment by KuZongFan** [comment]
OK, thanks
