### ISSUE TITLE
RuntimeError: invalid argument 2: A should be non-empty 2 dimensional

### ISSUE THREAD

**Issue by AmmonZ** [yewzijian/RPMNet#4]
when run 

python eval.py --noise_type crop --resume ./pretrained/partial-trained.pth --val_batch_size 8

I got:

RPMNet/src/models/rpmnet.py", line 133, in compute_rigid_transform
    u, s, v = torch.svd(cov, some=False, compute_uv=True)
RuntimeError: invalid argument 2: A should be non-empty 2 dimensional at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorMathMagma.cu:264

**Comment by yewzijian** [comment]
You need at least torch 1.2, otherwise it doesn't support batches for the SVD.
