### ISSUE TITLE
Question about the evaluation

### ISSUE THREAD

**Issue by Gilgamesh666666** [yewzijian/RPMNet#5]
Hi yewzijian:

Thank you for the sharing! I have a quesion when i read the code. In the evalution function, why you test the transformation matrix calculated in different iteration separeately? In my understand, the final transformation between the source and reference is the product of those transformation matrix calculated in different iteration, right？So  i am confused about the evaluation process.

`
def evaluate(pred_transforms, data_loader):
    _logger.info('Evaluating transforms...')
    num_processed, num_total = 0, len(pred_transforms)

    if pred_transforms.ndim == 4:
        pred_transforms = torch.from_numpy(pred_transforms).to(_device)
    else:
        assert pred_transforms.ndim == 3 and \
               (pred_transforms.shape[1:] == (4, 4) or pred_transforms.shape[1:] == (3, 4))
        pred_transforms = torch.from_numpy(pred_transforms[:, None, :, :]).to(_device)

    metrics_for_iter = [defaultdict(list) for _ in range(pred_transforms.shape[1])]

    for data in tqdm(data_loader, leave=False):
        dict_all_to_device(data, _device)

        batch_size = 0
        for i_iter in range(pred_transforms.shape[1]):
            batch_size = data['points_src'].shape[0]

            cur_pred_transforms = pred_transforms[num_processed:num_processed+batch_size, i_iter, :, :]
            metrics = compute_metrics(data, cur_pred_transforms)
            for k in metrics:
                metrics_for_iter[i_iter][k].append(metrics[k])
        num_processed += batch_size

    for i_iter in range(len(metrics_for_iter)):
        metrics_for_iter[i_iter] = {k: np.concatenate(metrics_for_iter[i_iter][k], axis=0)
                                    for k in metrics_for_iter[i_iter]}
        summary_metrics = summarize_metrics(metrics_for_iter[i_iter])
        print_metrics(_logger, summary_metrics, title='Evaluation result (iter {})'.format(i_iter))

    return metrics_for_iter, summary_metrics`

**Comment by yewzijian** [comment]
Hi, only the final iteration matters. The code evaluates previous iterations to understand how fast the registration converges (e.g. to generate Figure 4 in the paper).

So I believe you understood correctly. The final transformation already includes the incremental transformations from all the iterations.

**Comment by Gilgamesh666666** [comment]
I see, thanks for you reply!
